version: '3.8'

services:
  fullstack-app:
    image: fullstack-app-by-nx
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 4200:4200
    volumes:
      - .:/usr/src/app
      - .:/usr/src/app/nodes_modules
