version: '3.8'
services:
  frontend:
   build:
    context: ./
    dockerfile: 'Dockerfile-angular'
   ports:
    - '5000:80' # Map Nginx port 80 to host port 5000

  backend:
    build:
     context: ./
     dockerfile: 'Dockerfile-nestjs'
    ports:
      - '3000:3000' # Map Nest.js app port 3000 to host port 3000

  nginx:
    image: nginx:alpine
    container_name: fullstack-app
    ports:
      - '80:80' # Map Nginx port 80 to host port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
