# Build Stage
FROM docker.io/node:lts-alpine as build
RUN apk add g++ make py3-pip
WORKDIR /app
RUN npm install -g npm@9.6.7
COPY ["package.json", "package-lock.json","./"]
RUN npm cache verify
RUN npm install
RUN npm i -g @nrwl/cli pm2@latest
COPY ["nx.json", "./"]
COPY . .
RUN npx prisma generate
RUN npx nx run backend:build --configuration=development
# RUN pm2 start /app/dist/apps/backend/main.js -- --port 3000
EXPOSE 3000
# CMD ["pm2","start", "/app/dist/apps/backend/main.js","--","--port","3000"]
CMD ["node","/app/dist/apps/backend/main.js"]